<a href="https://colab.research.google.com/github/yiwenwangANU/pytorch/blob/main/PyTorch_0_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
tensor = torch.rand(3, 4)
tensor, tensor.ndim, tensor.shape

(tensor([[0.5740, 0.6112, 0.7593, 0.9389],
         [0.9893, 0.3476, 0.4085, 0.5784],
         [0.5256, 0.7014, 0.2980, 0.5560]]),
 2,
 torch.Size([3, 4]))

In [ ]:
tensor_float32 = torch.arange(1, 10, step=1, dtype=torch.float32, device=None, requires_grad=False)
tensor_float32

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
tensor_float16 = tensor_float32.to(torch.float16)
tensor_float16

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [ ]:
torch.matmul(tensor, tensor.T)  # 1. inner dims match 2. results have shape of outer dims

tensor([[2.1612, 1.6335, 1.4787],
        [1.6335, 1.6008, 1.2071],
        [1.4787, 1.2071, 1.1662]])

In [ ]:
tensor_1_1_12 = tensor.reshape(1, 1, 12)
tensor_1_1_12

tensor([[[0.5740, 0.6112, 0.7593, 0.9389, 0.9893, 0.3476, 0.4085, 0.5784,
          0.5256, 0.7014, 0.2980, 0.5560]]])

In [ ]:
tensor_4_3 = tensor_1_1_12.reshape(4, 3)
tensor_4_3

tensor([[0.5740, 0.6112, 0.7593],
        [0.9389, 0.9893, 0.3476],
        [0.4085, 0.5784, 0.5256],
        [0.7014, 0.2980, 0.5560]])

In [ ]:
tensor_squeeze = tensor_1_1_12.squeeze()
tensor_squeeze

tensor([0.5740, 0.6112, 0.7593, 0.9389, 0.9893, 0.3476, 0.4085, 0.5784, 0.5256,
        0.7014, 0.2980, 0.5560])

In [ ]:
tensor_unsqueeze = tensor_squeeze.unsqueeze(dim=0)
tensor_unsqueeze

tensor([[0.5740, 0.6112, 0.7593, 0.9389, 0.9893, 0.3476, 0.4085, 0.5784, 0.5256,
         0.7014, 0.2980, 0.5560]])

In [ ]:
# Create a 4D tensor with shape [batch, height, width, channels]
# Assume batch=2, height=20, width=20, channels=3
x = torch.randn(2, 20, 20, 3)
print("Original tensor shape:", x.shape)

# Permute to change the tensor to [batch, channels, height, width]
x_permuted = x.permute(0, 3, 1, 2)
print("Permuted tensor shape:", x_permuted.shape)

## Permute return a view of x, which means it will change the value of original if its value changes

Original tensor shape: torch.Size([2, 20, 20, 3])
Permuted tensor shape: torch.Size([2, 3, 20, 20])


In [1]:
import torch

torch.rand(3, 3)

tensor([[0.5587, 0.0053, 0.1830],
        [0.8970, 0.0722, 0.6939],
        [0.9355, 0.8369, 0.1814]])

In [3]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(3, 3)
torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(3, 3)
print(tensor_A)
print(tensor_B)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


In [8]:
import torch

torch.manual_seed(0)
tensor_A = torch.rand(7, 7)
torch.manual_seed(0)
tensor_B = torch.rand(1, 7)
result = torch.matmul(tensor_A, tensor_B.T)
print(result)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


In [4]:
import torch

torch.manual_seed(1234)
tensor_A = torch.rand(2, 3).to('cuda')
tensor_B = torch.rand(2, 3).to('cuda')
tensor_A, tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [5]:
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [6]:
max_value = torch.max(tensor_C)
max_index = torch.argmax(tensor_C)
max_value, max_index

(tensor(0.5617, device='cuda:0'), tensor(3, device='cuda:0'))

In [8]:
import torch

torch.manual_seed(7)
rand_tensor = torch.rand(1, 1, 1, 10)
squeezed_tensor = rand_tensor.squeeze()
rand_tensor, squeezed_tensor

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))